---
title: "plotly"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(p8105.datasets)
library(plotly)

data("rest_inspec")
```

Tidying

```{r}
rest_inspec =
  rest_inspec %>% 
  janitor::clean_names() %>%
  drop_na()
```

Scatterplot of latitude vs. longitude, colored by grade

```{r}
rest_inspec %>%
  mutate(
    label = str_c("Borough: ", boro, "\nScore: ", score)
  ) %>% 
  plot_ly(
    x = ~latitude, y = ~longitude, color = ~grade, text = ~label,
    type = "scatter", mode = "markers", alpha = 0.5
  )
```

Box plot; restaurants in Manhattan with pending grades and their scores

```{r}
rest_inspec %>%
  filter(
    boro == "Manhattan",
    cuisine_description == "Café/Coffee/Tea",
    grade == "P"
  ) %>%
  mutate(
    dba = fct_reorder(dba, score)
  ) %>% 
  plot_ly(
    y = ~score, color = ~dba,
    type = "box",
    colors = "viridis",
    width = 650, height = 300
  ) %>% 
  layout(
    xaxis = list(title = 'Name of Restaurant/Entity'), 
    yaxis = list(title = 'Score')
    )
```

Frequency of grades for restaurants in Manhattan

```{r}
rest_inspec %>%
  filter(
    boro == "Manhattan",
  ) %>% 
  count(grade) %>% 
  mutate(
    grade = fct_reorder(grade, n)
  ) %>% 
  plot_ly(
    x = ~grade, y = ~n, color = ~grade,
    type = "bar",
    colors = "viridis"
  )
```